# render.yaml
services:
  - type: web
    name: stone-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    buildFilter:
      paths:
        - frontend/**

  - type: web
    name: stone-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    buildFilter:
      paths:
        - backend/**
