"""Set user_type default to USER

Revision ID: XXXXXXXXXXXX
Revises: 53176f4797b6
Create Date: 2025-07-18 ...

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Import if using ENUM

# revision identifiers, used by Alembic.
revision: str = 'XXXXXXXXXXXX' # Your new revision ID
down_revision: Union[str, Sequence[str], None] = '53176f4797b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set the new server default for the 'user_type' column
    op.alter_column(
        'users',
        'user_type',
        existing_type=postgresql.ENUM('USER', 'DESIGNER', 'ARCHITECT', 'SUPERADMIN', 'DISTRIBUTOR', name='user_type'),
        server_default=sa.text("'USER'"), # The new default
        existing_server_default=sa.text("'DESIGNER'"), # The old default Alembic should revert from
        nullable=False # Keep current nullable status
    )

    # Optional: If you want to update EXISTING rows that might have 'DESIGNER' to 'USER'
    # Only run this if you want to modify existing data in your current database!
    op.execute("UPDATE users SET user_type = 'USER' WHERE user_type = 'DESIGNER';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the server default back to 'DESIGNER'
    op.alter_column(
        'users',
        'user_type',
        existing_type=postgresql.ENUM('USER', 'DESIGNER', 'ARCHITECT', 'SUPERADMIN', 'DISTRIBUTOR', name='user_type'),
        server_default=sa.text("'DESIGNER'"), # Revert to old default
        existing_server_default=sa.text("'USER'"), # The current default
        nullable=False
    )

    # Optional: If you want to revert EXISTING rows from 'USER' to 'DESIGNER' during downgrade
    # Only run this if you want to modify existing data when downgrading!
    # op.execute("UPDATE users SET user_type = 'DESIGNER' WHERE user_type = 'USER';")

    # ### end Alembic commands ###